name: llama.cpp (CPU, GPU, iGPU)
description: Run large language models locally using llama.cpp. Features full hardware acceleration via Vulkan (AMD/Nvidia GPUs) and SYCL (Intel iGPUs), plus advanced Speculative Decoding.
version: "1.4.0"
slug: llamacpp
arch:
- aarch64
- amd64
url: https://github.com/ggerganov/llama.cpp
map:
- config:rw
- share:rw
- data:rw
init: false
ingress: true
legacy: true
ingress_port: 8081
ingress_stream: true
ports:
  8080/tcp: 8080
  8081/tcp: null
ports_description:
  8080/tcp: The llama.cpp server API Port
  8081/tcp: The Management Web UI Port
options:
  LLAMACPP_MODEL_DIR: /share/llamacpp
  MODELS:
  - LLAMACPP_USE_CASE: text
    LLAMACPP_MODEL: ''
    LLAMACPP_DISABLE_REASONING: false
    LLAMACPP_DRAFTER: ''
    LLAMACPP_DRAFTER_TYPE: none
    LLAMACPP_DRAFT_MIN: 5
    LLAMACPP_DRAFT_MAX: 16
    LLAMACPP_EXTRA_ARGS: ''
  LLAMACPP_VULKAN: true
  LLAMACPP_SYCL: false
  LLAMACPP_GPU_PATH: /dev/dri/renderD128
  LLAMACPP_CTX_SIZE: 4096
  LLAMACPP_THREADS: 4
  LLAMACPP_BATCH_SIZE: 512
  LLAMACPP_PARALLEL: 1
  LLAMACPP_FLASH_ATTN: true
  LLAMACPP_KV_CACHE_TYPE: f16
  LLAMACPP_HF_TOKEN: ''
  gpus: all
schema:
  LLAMACPP_MODEL_DIR: list(/config/llamacpp|/share/llamacpp|/data/llamacpp)
  MODELS:
  - LLAMACPP_USE_CASE: list(text|vision)
    LLAMACPP_MODEL: match(^[^/]+/[^/]+:.+$)
    LLAMACPP_DISABLE_REASONING: bool
    LLAMACPP_DRAFTER: match(^([^/]+/[^/]+:.+)?$)
    LLAMACPP_DRAFTER_TYPE: list(none|mtp|dflash|dspark)
    LLAMACPP_DRAFT_MIN: int?
    LLAMACPP_DRAFT_MAX: int?
    LLAMACPP_EXTRA_ARGS: str?
  LLAMACPP_VULKAN: bool
  LLAMACPP_SYCL: bool
  LLAMACPP_GPU_PATH: str
  LLAMACPP_CTX_SIZE: int
  LLAMACPP_THREADS: int
  LLAMACPP_BATCH_SIZE: int
  LLAMACPP_PARALLEL: int
  LLAMACPP_FLASH_ATTN: bool
  LLAMACPP_KV_CACHE_TYPE: list(f16|f32|q8_0|q4_0|q4_1)
  LLAMACPP_HF_TOKEN: match(^(hf_.+)?$)
  gpus: str
video: true
startup: application
watchdog: tcp://[HOST]:[PORT:8080]
