#!/usr/bin/env bash
set -e

CONFIG_PATH="/data/options.json"

# Export HF token if provided
HF_TOKEN=$(jq --raw-output '.LLAMACPP_HF_TOKEN // empty' "$CONFIG_PATH")
if [ -n "$HF_TOKEN" ]; then
    export HF_TOKEN="$HF_TOKEN"
    echo "Hugging Face token provided."
fi

# 1. Pull models and generate execution config
echo "Starting model pull process..."
python3 /pull_models.py

# Read execution configuration generated by the python script
EXEC_CONFIG="/tmp/exec_config.json"
if [ ! -f "$EXEC_CONFIG" ]; then
    echo "Execution configuration not found. Model pull failed."
    exit 1
fi

MODEL=$(jq --raw-output '.model // empty' "$EXEC_CONFIG")
MMPROJ=$(jq --raw-output '.mmproj // empty' "$EXEC_CONFIG")
DRAFTER=$(jq --raw-output '.drafter // empty' "$EXEC_CONFIG")
DRAFTER_TYPE=$(jq --raw-output '.drafter_type // empty' "$EXEC_CONFIG")

# Read server options from user config
PORT=$(jq --raw-output '.ingress_port // 8080' "$CONFIG_PATH")
CTX_SIZE=$(jq --raw-output '.LLAMACPP_CTX_SIZE // 4096' "$CONFIG_PATH")
THREADS=$(jq --raw-output '.LLAMACPP_THREADS // 4' "$CONFIG_PATH")
BATCH_SIZE=$(jq --raw-output '.LLAMACPP_BATCH_SIZE // 512' "$CONFIG_PATH")
PARALLEL=$(jq --raw-output '.LLAMACPP_PARALLEL // 1' "$CONFIG_PATH")
USE_VULKAN=$(jq --raw-output '.LLAMACPP_VULKAN // "true"' "$CONFIG_PATH")
GPU_PATH=$(jq --raw-output '.LLAMACPP_GPU_PATH // "/dev/dri/renderD128"' "$CONFIG_PATH")
FLASH_ATTN=$(jq --raw-output '.LLAMACPP_FLASH_ATTN // "false"' "$CONFIG_PATH")

# Determine which binary to use
SERVER_DIR="/opt/llama.cpp/build-cpu"
BINARY="$SERVER_DIR/llama-server"
if [ "$USE_VULKAN" = "true" ]; then
    echo "Vulkan enabled. Verifying GPU..."
    if [ -e "$GPU_PATH" ]; then
        echo "GPU found at $GPU_PATH. Using Vulkan binary."
        SERVER_DIR="/opt/llama.cpp/build-vulkan"
        BINARY="$SERVER_DIR/llama-server"
    else
        echo "WARNING: GPU path $GPU_PATH not found! Falling back to CPU binary."
    fi
fi

# Set library path so the server can find its .so files (libggml, libllama, etc)
export LD_LIBRARY_PATH="$SERVER_DIR:$LD_LIBRARY_PATH"

CMD=("$BINARY" "--host" "0.0.0.0" "--port" "$PORT" "-m" "$MODEL" "-c" "$CTX_SIZE" "-t" "$THREADS" "-b" "$BATCH_SIZE" "--parallel" "$PARALLEL" "--path" "/opt/llama.cpp/public" "--metrics")

if [ "$FLASH_ATTN" = "true" ]; then
    CMD+=("--flash-attn" "on")
fi

if [ -n "$MMPROJ" ] && [ "$MMPROJ" != "null" ]; then
    echo "Adding mmproj: $MMPROJ"
    CMD+=("--mmproj" "$MMPROJ")
fi

HAS_EXTERNAL_DRAFTER=false
if [ -n "$DRAFTER" ] && [ "$DRAFTER" != "null" ]; then
    echo "Adding Drafter Model: $DRAFTER"
    CMD+=("-md" "$DRAFTER")
    HAS_EXTERNAL_DRAFTER=true
fi

if [ -n "$DRAFTER_TYPE" ] && [ "$DRAFTER_TYPE" != "none" ]; then
    if [ "$DRAFTER_TYPE" = "mtp" ]; then
        if [ "$HAS_EXTERNAL_DRAFTER" = "true" ]; then
            echo "Enabling External MTP Speculative Decoding"
            CMD+=("--spec-type" "draft-mtp")
        else
            echo "Enabling Self-Speculative Decoding (MTP)"
            CMD+=("--spec-type" "mtp")
        fi
    else
        echo "Adding Speculative Decoding Type: $DRAFTER_TYPE"
        CMD+=("--spec-type" "draft-$DRAFTER_TYPE")
    fi
fi

echo "Starting server with command: ${CMD[*]}"
exec "${CMD[@]}"
