#!/usr/bin/env bash
set -e

CONFIG_PATH="/data/options.json"

# Export HF token if provided
HF_TOKEN=$(jq --raw-output '.LLAMACPP_HF_TOKEN // empty' "$CONFIG_PATH")
if [ -n "$HF_TOKEN" ]; then
    export HF_TOKEN="$HF_TOKEN"
    echo "Hugging Face token provided."
fi

# 1. Pull models and generate execution config
echo "Starting model pull process..."
python3 /pull_models.py

# Read execution configuration generated by the python script
EXEC_CONFIG="/tmp/exec_config.json"
if [ ! -f "$EXEC_CONFIG" ]; then
    echo "Execution configuration not found. Model pull failed."
    exit 1
fi

MODEL=$(jq --raw-output '.model // empty' "$EXEC_CONFIG")
MMPROJ=$(jq --raw-output '.mmproj // empty' "$EXEC_CONFIG")
DRAFTER=$(jq --raw-output '.drafter // empty' "$EXEC_CONFIG")
DRAFTER_TYPE=$(jq --raw-output '.drafter_type // empty' "$EXEC_CONFIG")

UPDATE_ON_BOOT=$(jq --raw-output '.LLAMACPP_UPDATE_ON_BOOT // "false"' "$CONFIG_PATH")

if [ "$UPDATE_ON_BOOT" = "true" ]; then
    echo "=================================================="
    echo "Update on Boot enabled! Fetching latest llama.cpp..."
    echo "=================================================="
    ARCH=$(dpkg --print-architecture)
    if [ "$ARCH" = "amd64" ]; then LLAMA_ARCH="x64";
    elif [ "$ARCH" = "arm64" ]; then LLAMA_ARCH="arm64";
    else echo "Unsupported architecture: $ARCH"; exit 1; fi
    
    LATEST_RELEASE=$(curl -s https://api.github.com/repos/ggml-org/llama.cpp/releases/latest)
    
    CPU_URL=$(echo "$LATEST_RELEASE" | grep -o "https://github.com/ggml-org/llama.cpp/releases/download/[^\"]*ubuntu-${LLAMA_ARCH}\.tar\.gz" | head -n 1)
    echo "Downloading updated CPU release: $CPU_URL"
    curl -sL -o /tmp/cpu.tar.gz "$CPU_URL"
    tar -xzf /tmp/cpu.tar.gz -C /opt/llama.cpp/build-cpu --strip-components=1
    
    VULKAN_URL=$(echo "$LATEST_RELEASE" | grep -o "https://github.com/ggml-org/llama.cpp/releases/download/[^\"]*ubuntu-vulkan-${LLAMA_ARCH}\.tar\.gz" | head -n 1)
    echo "Downloading updated Vulkan release: $VULKAN_URL"
    curl -sL -o /tmp/vulkan.tar.gz "$VULKAN_URL"
    tar -xzf /tmp/vulkan.tar.gz -C /opt/llama.cpp/build-vulkan --strip-components=1
    
    rm -f /tmp/cpu.tar.gz /tmp/vulkan.tar.gz
    echo "Update complete!"
fi

# Read server options from user config
PORT=$(jq --raw-output '.ingress_port // 8080' "$CONFIG_PATH")
CTX_SIZE=$(jq --raw-output '.LLAMACPP_CTX_SIZE // 4096' "$CONFIG_PATH")
THREADS=$(jq --raw-output '.LLAMACPP_THREADS // 4' "$CONFIG_PATH")
BATCH_SIZE=$(jq --raw-output '.LLAMACPP_BATCH_SIZE // 512' "$CONFIG_PATH")
PARALLEL=$(jq --raw-output '.LLAMACPP_PARALLEL // 1' "$CONFIG_PATH")
USE_VULKAN=$(jq --raw-output '.LLAMACPP_VULKAN // "true"' "$CONFIG_PATH")
GPU_PATH=$(jq --raw-output '.LLAMACPP_GPU_PATH // "/dev/dri/renderD128"' "$CONFIG_PATH")
FLASH_ATTN=$(jq --raw-output '.LLAMACPP_FLASH_ATTN // "false"' "$CONFIG_PATH")

# Determine which binary to use
SERVER_DIR="/opt/llama.cpp/build-cpu"
BINARY="$SERVER_DIR/llama-server"
if [ "$USE_VULKAN" = "true" ]; then
    echo "Vulkan enabled. Verifying GPU..."
    if [ -e "$GPU_PATH" ]; then
        echo "GPU found at $GPU_PATH. Using Vulkan binary."
        SERVER_DIR="/opt/llama.cpp/build-vulkan"
        BINARY="$SERVER_DIR/llama-server"
    else
        echo "WARNING: GPU path $GPU_PATH not found! Falling back to CPU binary."
    fi
fi

# Set library path so the server can find its .so files (libggml, libllama, etc)
export LD_LIBRARY_PATH="$SERVER_DIR:$LD_LIBRARY_PATH"

CMD=("$BINARY" "--host" "0.0.0.0" "--port" "$PORT" "-m" "$MODEL" "-c" "$CTX_SIZE" "-t" "$THREADS" "-b" "$BATCH_SIZE" "--parallel" "$PARALLEL" "--path" "/opt/llama.cpp/public" "--metrics")

if [ "$FLASH_ATTN" = "true" ]; then
    CMD+=("--flash-attn" "on")
fi

if [ -n "$MMPROJ" ] && [ "$MMPROJ" != "null" ]; then
    echo "Adding mmproj: $MMPROJ"
    CMD+=("--mmproj" "$MMPROJ")
fi

HAS_EXTERNAL_DRAFTER=false
if [ -n "$DRAFTER" ] && [ "$DRAFTER" != "null" ]; then
    echo "Adding Drafter Model: $DRAFTER"
    CMD+=("-md" "$DRAFTER")
    HAS_EXTERNAL_DRAFTER=true
fi

if [ -n "$DRAFTER_TYPE" ] && [ "$DRAFTER_TYPE" != "none" ]; then
    if [ "$HAS_EXTERNAL_DRAFTER" = "true" ]; then
        echo "Enabling External Speculative Decoding: $DRAFTER_TYPE"
    else
        echo "Enabling Self-Speculative Decoding: $DRAFTER_TYPE"
    fi
    CMD+=("--spec-type" "draft-$DRAFTER_TYPE")
fi

echo "Starting server with command: ${CMD[*]}"
exec "${CMD[@]}"
