#!/usr/bin/env bash
set -e

CONFIG_PATH="/data/options.json"

# Export HF token if provided
HF_TOKEN=$(jq --raw-output '.LLAMACPP_HF_TOKEN // empty' "$CONFIG_PATH")
if [ -n "$HF_TOKEN" ]; then
    export HF_TOKEN="$HF_TOKEN"
    echo "Hugging Face token provided."
fi

# 1. Pull models and generate execution config
echo "Starting model pull process..."
python3 /pull_models.py

# Read execution configuration generated by the python script
EXEC_CONFIG="/tmp/exec_config.json"
if [ ! -f "$EXEC_CONFIG" ]; then
    echo "Execution configuration not found. Model pull failed."
    exit 1
fi

VERSION=$(cat /opt/llama.cpp/llama_version.txt)
BIN_DIR="/data/llamacpp-bin/${VERSION}"
LLAMA_SERVER_CPU="${BIN_DIR}/build-cpu/llama-server"
LLAMA_SERVER_VULKAN="${BIN_DIR}/build-vulkan/llama-server"
LLAMA_SERVER_SYCL="${BIN_DIR}/build-sycl/llama-server"

if [ ! -f "$LLAMA_SERVER_CPU" ] || [ ! -f "$LLAMA_SERVER_VULKAN" ] || [ ! -f "$LLAMA_SERVER_SYCL" ]; then
    echo "=================================================="
    echo "Fetching llama.cpp version ${VERSION}..."
    echo "=================================================="
    ARCH=$(dpkg --print-architecture)
    if [ "$ARCH" = "amd64" ]; then LLAMA_ARCH="x64";
    elif [ "$ARCH" = "arm64" ]; then LLAMA_ARCH="arm64";
    else echo "Unsupported architecture: $ARCH"; exit 1; fi
    
    mkdir -p "${BIN_DIR}/build-cpu" "${BIN_DIR}/build-vulkan"
    
    # Resolve meta-releases (like v0.2.0) to their actual binary tag (like b10566)
    BIN_VERSION="$VERSION"
    NIGHTLY_TXT_URL="https://github.com/ggml-org/llama.cpp/releases/download/${VERSION}/nightly-tag.txt"
    if curl -sI "$NIGHTLY_TXT_URL" | grep -iq "HTTP/.* 200\|HTTP/.* 302"; then
        BIN_VERSION=$(curl -sL "$NIGHTLY_TXT_URL" | tr -d '[:space:]')
        echo "Resolved meta-release ${VERSION} to binary tag ${BIN_VERSION}"
    fi
    
    CPU_URL="https://github.com/ggml-org/llama.cpp/releases/download/${BIN_VERSION}/llama-${BIN_VERSION}-bin-ubuntu-${LLAMA_ARCH}.tar.gz"
    echo "Downloading CPU release: $CPU_URL"
    curl -sL -o /tmp/cpu.tar.gz "$CPU_URL"
    tar -xzf /tmp/cpu.tar.gz -C "${BIN_DIR}/build-cpu" --strip-components=1
    
    VULKAN_URL="https://github.com/ggml-org/llama.cpp/releases/download/${BIN_VERSION}/llama-${BIN_VERSION}-bin-ubuntu-vulkan-${LLAMA_ARCH}.tar.gz"
    echo "Downloading Vulkan release: $VULKAN_URL"
    curl -sL -o /tmp/vulkan.tar.gz "$VULKAN_URL"
    tar -xzf /tmp/vulkan.tar.gz -C "${BIN_DIR}/build-vulkan" --strip-components=1
    
    SYCL_URL="https://github.com/ggml-org/llama.cpp/releases/download/${BIN_VERSION}/llama-${BIN_VERSION}-bin-ubuntu-sycl-fp16-${LLAMA_ARCH}.tar.gz"
    echo "Downloading SYCL release: $SYCL_URL"
    mkdir -p "${BIN_DIR}/build-sycl"
    curl -sL -o /tmp/sycl.tar.gz "$SYCL_URL"
    tar -xzf /tmp/sycl.tar.gz -C "${BIN_DIR}/build-sycl" --strip-components=1 || echo "Warning: SYCL binary failed to extract."
    
    rm -f /tmp/cpu.tar.gz /tmp/vulkan.tar.gz /tmp/sycl.tar.gz
    echo "Download complete!"
fi

# Read server options from user config
PORT=$(jq --raw-output '.ingress_port // 8080' "$CONFIG_PATH")
CTX_SIZE=$(jq --raw-output '.LLAMACPP_CTX_SIZE // 4096' "$CONFIG_PATH")
THREADS=$(jq --raw-output '.LLAMACPP_THREADS // 4' "$CONFIG_PATH")
BATCH_SIZE=$(jq --raw-output '.LLAMACPP_BATCH_SIZE // 512' "$CONFIG_PATH")
PARALLEL=$(jq --raw-output '.LLAMACPP_PARALLEL // 1' "$CONFIG_PATH")
USE_SYCL=$(jq --raw-output 'if has("LLAMACPP_SYCL") then .LLAMACPP_SYCL else "false" end' "$CONFIG_PATH")
USE_VULKAN=$(jq --raw-output 'if has("LLAMACPP_VULKAN") then .LLAMACPP_VULKAN else "true" end' "$CONFIG_PATH")
GPU_PATH=$(jq --raw-output '.LLAMACPP_GPU_PATH // "/dev/dri/renderD128"' "$CONFIG_PATH")
FLASH_ATTN=$(jq --raw-output 'if has("LLAMACPP_FLASH_ATTN") then .LLAMACPP_FLASH_ATTN else "false" end' "$CONFIG_PATH")
KV_CACHE_TYPE=$(jq --raw-output 'if has("LLAMACPP_KV_CACHE_TYPE") then .LLAMACPP_KV_CACHE_TYPE else "f16" end' "$CONFIG_PATH")

# Determine which binary to use
SERVER_DIR="${BIN_DIR}/build-cpu"
BINARY="$SERVER_DIR/llama-server"

if [ "$USE_SYCL" = "true" ]; then
    echo "Intel SYCL enabled! Using highly optimized oneAPI backend."
    SERVER_DIR="${BIN_DIR}/build-sycl"
    BINARY="$SERVER_DIR/llama-server"
    if [ -f "/opt/intel/oneapi/setvars.sh" ]; then
        source /opt/intel/oneapi/setvars.sh
    fi
    
    # setvars.sh may not be present in minimal runtime installs, so we manually
    # find and append all Intel library directories to ensure libsvml.so is found
    if [ -d "/opt/intel" ]; then
        INTEL_LIBS=$(find /opt/intel -name "*.so*" -exec dirname {} \; | sort -u | tr '\n' ':')
        export LD_LIBRARY_PATH="$INTEL_LIBS$LD_LIBRARY_PATH"
    fi
elif [ "$USE_VULKAN" = "true" ]; then
    echo "Vulkan enabled. Verifying GPU..."
    if [ -e "$GPU_PATH" ]; then
        echo "GPU found at $GPU_PATH. Using Vulkan binary."
        SERVER_DIR="${BIN_DIR}/build-vulkan"
        BINARY="$SERVER_DIR/llama-server"
    else
        echo "WARNING: GPU path $GPU_PATH not found! Falling back to CPU binary."
    fi
else
    echo "Vulkan & SYCL disabled by configuration. Using CPU binary."
fi

# Set library path so the server can find its .so files (libggml, libllama, etc)
export LD_LIBRARY_PATH="$SERVER_DIR:$LD_LIBRARY_PATH"

# Generate presets.ini
# Iterate over JSON array
NUM_MODELS=$(jq '. | length' "$EXEC_CONFIG")
if [ "$NUM_MODELS" -eq 0 ]; then
    echo "No models configured in exec config!"
    exit 1
fi

CMD=("$BINARY" "--host" "0.0.0.0" "--port" "$PORT" "-c" "$CTX_SIZE" "-t" "$THREADS" "-b" "$BATCH_SIZE" "--parallel" "$PARALLEL" "--path" "/opt/llama.cpp/public" "--metrics" "-ctk" "$KV_CACHE_TYPE" "-ctv" "$KV_CACHE_TYPE")

if [ "$FLASH_ATTN" = "true" ]; then
    CMD+=("--flash-attn" "on")
fi

# Extract and apply speculative decoding limits and extra args from the first model config
DRAFT_MIN=$(jq --raw-output ".[0].draft_min // empty" "$EXEC_CONFIG")
DRAFT_MAX=$(jq --raw-output ".[0].draft_max // empty" "$EXEC_CONFIG")
EXTRA_ARGS=$(jq --raw-output ".[0].extra_args // empty" "$EXEC_CONFIG")

if [ -n "$DRAFT_MIN" ] && [ "$DRAFT_MIN" != "null" ]; then
    CMD+=("--spec-draft-n-min" "$DRAFT_MIN")
fi
if [ -n "$DRAFT_MAX" ] && [ "$DRAFT_MAX" != "null" ]; then
    CMD+=("--spec-draft-n-max" "$DRAFT_MAX")
fi
if [ -n "$EXTRA_ARGS" ] && [ "$EXTRA_ARGS" != "null" ]; then
    # Properly split by spaces so arguments are handled correctly
    read -ra EXTRA_ARGS_ARRAY <<< "$EXTRA_ARGS"
    CMD+=("${EXTRA_ARGS_ARRAY[@]}")
fi

if [ "$NUM_MODELS" -eq 1 ]; then
    echo "Single model detected. Bypassing Router Mode for backwards compatibility."
    MODEL=$(jq --raw-output ".[0].model // empty" "$EXEC_CONFIG")
    MMPROJ=$(jq --raw-output ".[0].mmproj // empty" "$EXEC_CONFIG")
    DRAFTER=$(jq --raw-output ".[0].drafter // empty" "$EXEC_CONFIG")
    DRAFTER_TYPE=$(jq --raw-output ".[0].drafter_type // empty" "$EXEC_CONFIG")
    DISABLE_REASONING=$(jq --raw-output ".[0].disable_reasoning // false" "$EXEC_CONFIG")
    
    CMD+=("-m" "$MODEL")
    
    if [ "$DISABLE_REASONING" = "true" ]; then
        echo "Disabling reasoning"
        CMD+=("--reasoning" "off")
    fi
    
    if [ -n "$MMPROJ" ] && [ "$MMPROJ" != "null" ]; then
        echo "Adding mmproj: $MMPROJ"
        CMD+=("--mmproj" "$MMPROJ")
    fi
    
    HAS_EXTERNAL_DRAFTER="false"
    if [ -n "$DRAFTER" ] && [ "$DRAFTER" != "null" ]; then
        echo "Adding Drafter Model: $DRAFTER"
        CMD+=("-md" "$DRAFTER")
        HAS_EXTERNAL_DRAFTER="true"
    fi
    
    if [ -n "$DRAFTER_TYPE" ] && [ "$DRAFTER_TYPE" != "none" ]; then
        if [ "$HAS_EXTERNAL_DRAFTER" = "true" ]; then
            echo "Enabling External Speculative Decoding: $DRAFTER_TYPE"
        else
            echo "Enabling Self-Speculative Decoding: $DRAFTER_TYPE"
        fi
        CMD+=("--spec-type" "draft-$DRAFTER_TYPE")
    fi
else
    echo "Multiple models detected. Enabling Router Mode."
    PRESET_FILE="/tmp/presets.ini"
    rm -f "$PRESET_FILE"

    for i in $(seq 0 $((NUM_MODELS-1))); do
        MODEL=$(jq --raw-output ".[$i].model // empty" "$EXEC_CONFIG")
        MMPROJ=$(jq --raw-output ".[$i].mmproj // empty" "$EXEC_CONFIG")
        DRAFTER=$(jq --raw-output ".[$i].drafter // empty" "$EXEC_CONFIG")
        DRAFTER_TYPE=$(jq --raw-output ".[$i].drafter_type // empty" "$EXEC_CONFIG")
        DISABLE_REASONING=$(jq --raw-output ".[$i].disable_reasoning // false" "$EXEC_CONFIG")
        
        # Extract filename from path for the preset section header
        MODEL_NAME=$(basename "$MODEL" | sed 's/\.gguf$//')
        
        echo "[$MODEL_NAME]" >> "$PRESET_FILE"
        echo "model = $MODEL" >> "$PRESET_FILE"
        
        if [ "$DISABLE_REASONING" = "true" ]; then
            echo "reasoning = off" >> "$PRESET_FILE"
        fi
        
        if [ -n "$MMPROJ" ] && [ "$MMPROJ" != "null" ]; then
            echo "mmproj = $MMPROJ" >> "$PRESET_FILE"
        fi
        
        HAS_EXTERNAL_DRAFTER="false"
        if [ -n "$DRAFTER" ] && [ "$DRAFTER" != "null" ]; then
            echo "model-draft = $DRAFTER" >> "$PRESET_FILE"
            HAS_EXTERNAL_DRAFTER="true"
        fi
        
        if [ -n "$DRAFTER_TYPE" ] && [ "$DRAFTER_TYPE" != "none" ]; then
            echo "spec-type = draft-$DRAFTER_TYPE" >> "$PRESET_FILE"
        fi
        echo "" >> "$PRESET_FILE"
    done
    
    CMD+=("--models-preset" "$PRESET_FILE")
    echo "Generated presets.ini:"
    cat "$PRESET_FILE"
fi

echo "Starting server with command: ${CMD[*]}"
exec "${CMD[@]}"
